### PR TITLE
[SOLVE] BOJ 2606_Virus

### PR DESCRIPTION
**Pull request by dev-thug**
I solved the problem using bfs algorithm of graph searching

The problem link is https://www.acmicpc.net/problem/2606

### CODE REVIEW

**Comment by dev-thug** [comment]
@hyeonjini @JaeyeonG1 
Hey, Bros.... Would you like to review this code running in nodejs?

**Comment by hyeonjini** [comment]
Please typescript

**Comment by dev-thug** [comment]
I also know js is fxck up lang.
so, i update the js to ts. Please review it. 😅

**Review by hyeonjini — APPROVED** [review]
LGTM👍

**Review by hyeonjini — APPROVED** [review]
LGTM👍

**Pull request merged**
